### ISSUE TITLE
cannot load such file -- models/free_text (LoadError)

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/file-parser#4]
When I do

```
git clone https://github.com/dtu-compute/file-parser.git
cd file-parser
git checkout develop
docker build -t test2 .
```

I get

```
Sending build context to Docker daemon 372.2 kB
Sending build context to Docker daemon 
Step 0 : FROM fedora:22
 ---> ded7cd95e059
Step 1 : RUN dnf -y update
 ---> Using cache
 ---> 5d989bd2c2c2
Step 2 : RUN dnf -y install ruby ruby-devel git make gcc &&    dnf clean all
 ---> Using cache
 ---> 7cf9f073c149
Step 3 : COPY . /quiz/
 ---> 321783e86cc5
Removing intermediate container 786339b46912
Step 4 : WORKDIR /quiz
 ---> Running in 779da9812d17
 ---> 09ab24262979
Removing intermediate container 779da9812d17
Step 5 : RUN gem install bundle &&    bundle install &&    rspec &&    gem build quiz.gemspec &&    gem install quiz-0.1.0.gem
 ---> Running in c125e618e723
Successfully installed bundler-1.10.6
Successfully installed bundle-0.0.1
Parsing documentation for bundler-1.10.6
Installing ri documentation for bundler-1.10.6
Parsing documentation for bundle-0.0.1
Installing ri documentation for bundle-0.0.1
Done installing documentation for bundler, bundle after 6 seconds
2 gems installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Using json 1.8.3
Installing minitest 5.8.3
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.5
Installing builder 3.2.2
Installing activemodel 4.2.5
Installing awesome_print 1.6.1
Using bundler 1.10.6
Installing coderay 1.1.0
Installing diff-lcs 1.2.5
Installing method_source 0.8.2
Installing slop 3.6.0
Installing pry 0.10.3
Using quiz 0.1.0 from source at .
Installing rspec-support 3.4.1
Installing rspec-core 3.4.1
Installing rspec-expectations 3.4.0
Installing rspec-mocks 3.4.0
Installing rspec 3.4.0
Bundle complete! 7 Gemfile dependencies, 22 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- models/free_text (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /quiz/lib/quiz/parse_elements/question_elements/free_text.rb:6:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /quiz/lib/quiz/parse_elements/base_elements/survey.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /quiz/lib/quiz/quiz-parser.rb:5:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /quiz/lib/quiz.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /quiz/spec/spec_helper.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /quiz/spec/bad_scenarios_spec.rb:1:in `<top (required)>'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
	from /usr/local/bin/rspec:23:in `load'
	from /usr/local/bin/rspec:23:in `<main>'
The command '/bin/sh -c gem install bundle &&    bundle install &&    rspec &&    gem build quiz.gemspec &&    gem install quiz-0.1.0.gem' returned a non-zero code: 1
[root@enote file-parser]# 
```

**Comment by dtu-compute** [comment]
With the latest fix, I get a slightly different error.

```
[root@enote file-parser]# git pull
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11 (delta 6), reused 8 (delta 3), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/dtu-compute/file-parser
   563f861..dd801c3  develop    -> origin/develop
Updating 563f861..dd801c3
Fast-forward
 lib/models/free_text.rb | 22 ++++++++++++++++++++++
 lib/models/survey.rb    | 22 ++++++++++++++++++++++
 2 files changed, 44 insertions(+)
 create mode 100644 lib/models/free_text.rb
 create mode 100644 lib/models/survey.rb
[root@enote file-parser]# docker build -t test2 .
Sending build context to Docker daemon 396.3 kB
Sending build context to Docker daemon 
Step 0 : FROM fedora:22
 ---> ded7cd95e059
Step 1 : RUN dnf -y update
 ---> Using cache
 ---> a863b87036ac
Step 2 : RUN dnf -y install ruby ruby-devel git make gcc &&    dnf clean all
 ---> Using cache
 ---> f5792039b455
Step 3 : COPY . /quiz/
 ---> 0281bd357de3
Removing intermediate container b0503c9e6856
Step 4 : WORKDIR /quiz
 ---> Running in f102c35c0a37
 ---> 10a69364be71
Removing intermediate container f102c35c0a37
Step 5 : RUN gem install bundle &&    bundle install &&    rspec &&    gem build quiz.gemspec &&    gem install quiz-0.1.0.gem
 ---> Running in c95f11d1f6f7
Successfully installed bundler-1.10.6
Successfully installed bundle-0.0.1
Parsing documentation for bundler-1.10.6
Installing ri documentation for bundler-1.10.6
Parsing documentation for bundle-0.0.1
Installing ri documentation for bundle-0.0.1
Done installing documentation for bundler, bundle after 6 seconds
2 gems installed
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.4.2
Installing i18n 0.7.0
Using json 1.8.3
Installing minitest 5.8.3
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.5
Installing builder 3.2.2
Installing activemodel 4.2.5
Installing awesome_print 1.6.1
Using bundler 1.10.6
Installing coderay 1.1.0
Installing diff-lcs 1.2.5
Installing method_source 0.8.2
Installing slop 3.6.0
Installing pry 0.10.3
Using quiz 0.1.0 from source at .
Installing rspec-support 3.4.1
Installing rspec-core 3.4.1
Installing rspec-expectations 3.4.0
Installing rspec-mocks 3.4.0
Installing rspec 3.4.0
Bundle complete! 7 Gemfile dependencies, 22 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
/usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core.rb:178:in `block in const_missing': uninitialized constant RSpec::Pathname (NameError)
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core.rb:178:in `fetch'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core.rb:178:in `const_missing'
	from /quiz/spec/spec_helper.rb:13:in `root'
	from /quiz/spec/spec_helper.rb:19:in `testFilePath'
	from /quiz/spec/bad_scenarios_spec.rb:8:in `block (2 levels) in <top (required)>'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `module_exec'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
	from /quiz/spec/bad_scenarios_spec.rb:6:in `block in <top (required)>'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `module_exec'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:82:in `block (2 levels) in expose_example_group_alias_globally'
	from /quiz/spec/bad_scenarios_spec.rb:4:in `<top (required)>'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
	from /usr/local/share/gems/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
	from /usr/local/bin/rspec:23:in `load'
	from /usr/local/bin/rspec:23:in `<main>'
The command '/bin/sh -c gem install bundle &&    bundle install &&    rspec &&    gem build quiz.gemspec &&    gem install quiz-0.1.0.gem' returned a non-zero code: 1
[root@enote file-parser]# 
```
